### ISSUE TITLE
NVIDIA Tegra - Yocto Image Setup

### ISSUE THREAD

**Issue by suraj-ajjampur** [cu-ecen-aeld/final-project-aasu8675#1]
Performing the steps at [NVIDIA-Jetson-Nano-Deepstream---Docker-Example](https://github.com/cu-ecen-aeld/yocto-assignments-base/wiki/NVIDIA-Jetson-Nano-Deepstream---Docker-Example) to Build a Yocto Tegra Functional Image which serves as a Base Image for our Project

DoD:

- [x] Build Tegra Yocto Image on Host Machine
- [x] Flash the Image onto the Jetson Nano
- [x] Successfully boot-up the Board with Base Image

Blockers-
Incorrect poky URL discussed here.
https://discordapp.com/channels/1134815868996567090/1168263567557017741/1172692870403203182

**Comment by aasu8675** [comment]
Flashing for the Jetson Nano was successful through the host machine by using a USB cable.
<img width="803" alt="image" src="https://github.com/cu-ecen-aeld/final-project-aasu8675/assets/123521880/e7143d04-9a7c-4ef2-becc-4e137368c99f">




 Successful Boot-Up after flashing with Startup Screen can be seen below:
![image](https://github.com/cu-ecen-aeld/final-project-aasu8675/assets/123521880/6e8dba5a-0469-4401-9b07-08348e7eb6c6)

**Comment by aasu8675** [comment]
Tasks completed and DoD have been met.
